version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15.0
      steps: 
        - checkout
        - run: 
            command: npm install
        -run: 
            command: npm test